import { Role, User, Worker, Site, AttendanceEntry, AttendanceStatus, WorkerStatus, ReviewStatus, EngineerReview, Company } from './types';

// Mock Data
export const MOCK_COMPANY: Company = {
  id: 'c1',
  name: 'Demo Co',
  logo_url: 'https://picsum.photos/100',
  headcount: 100,
};

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Ali HR', email: 'hr@demo.co', password: 'password123', role: Role.HR, company_id: 'c1' },
  { id: 'u2', name: 'Hassan Foreman', email: 'foreman1@demo.co', password: 'password123', role: Role.Foreman, company_id: 'c1' },
  { id: 'u3', name: 'Khalid Foreman', email: 'foreman2@demo.co', password: 'password123', role: Role.Foreman, company_id: 'c1' },
  { id: 'u4', name: 'Fatima Engineer', email: 'engineer1@demo.co', password: 'password123', role: Role.Engineer, company_id: 'c1' },
  { id: 'u5', name: 'Yusuf Engineer', email: 'engineer2@demo.co', password: 'password123', role: Role.Engineer, company_id: 'c1' },
  { id: 'u6', name: 'Sara Accountant', email: 'accountant@demo.co', password: 'password123', role: Role.Accountant, company_id: 'c1' },
];

export const MOCK_SITES: Site[] = [
  { id: 's1', name: 'Site 102', company_id: 'c1', is_active: true },
  { id: 's2', name: 'Site 103', company_id: 'c1', is_active: true },
  { id: 's3', name: 'Workshop', company_id: 'c1', is_active: false },
];

export const MOCK_WORKERS: Worker[] = Array.from({ length: 12 }, (_, i) => ({
  id: `w${i + 1}`,
  full_name: `Worker ${String.fromCharCode(65 + i)}`,
  worker_code: `W-00${i + 1}`,
  start_date: `2023-01-${10 + i}`,
  status: WorkerStatus.Active,
  company_id: 'c1',
  site_id: i % 2 === 0 ? 's1' : 's2',
  foreman_id: i % 3 === 0 ? 'u2' : 'u3',
}));

export const MOCK_ATTENDANCE_ENTRIES: AttendanceEntry[] = [
  { id: 'e1', worker_id: 'w1', date: '2024-07-26', status: AttendanceStatus.Present, site_id: 's1', overtime_hours: 2 },
  { id: 'e2', worker_id: 'w2', date: '2024-07-26', status: AttendanceStatus.Present, site_id: 's2' },
  { id: 'e3', worker_id: 'w3', date: '2024-07-26', status: AttendanceStatus.AnnualLeave },
  { id: 'e4', worker_id: 'w4', date: '2024-07-27', status: AttendanceStatus.Present, site_id: 's1', overtime_hours: 8.5 },
  { id: 'e5', worker_id: 'w1', date: '2024-07-27', status: AttendanceStatus.SickLeave },
];

export const MOCK_ENGINEER_REVIEW: EngineerReview = {
  id: 'er1',
  cycle_id: 'cycle-2024-7',
  engineer_id: 'u4',
  status: ReviewStatus.Returned,
  signed_at: new Date().toISOString(),
  hr_notes: "Please double check worker W-004's overtime on 2024-07-27. It seems high."
};

export const ATTENDANCE_STATUS_OPTIONS = Object.values(AttendanceStatus).filter(s => s !== AttendanceStatus.Weekend);
export const ATTENDANCE_STATUS_COLORS: Record<AttendanceStatus | '', string> = {
  [AttendanceStatus.Present]: 'bg-green-100 dark:bg-green-800 text-green-800 dark:text-green-200',
  [AttendanceStatus.Absent]: 'bg-red-100 dark:bg-red-800 text-red-800 dark:text-red-200',
  [AttendanceStatus.AnnualLeave]: 'bg-blue-100 dark:bg-blue-800 text-blue-800 dark:text-blue-200',
  [AttendanceStatus.SickLeave]: 'bg-yellow-100 dark:bg-yellow-800 text-yellow-800 dark:text-yellow-200',
  [AttendanceStatus.EmergencyLeave]: 'bg-orange-100 dark:bg-orange-800 text-orange-800 dark:text-orange-200',
  [AttendanceStatus.UnpaidLeave]: 'bg-gray-200 dark:bg-gray-600 text-gray-800 dark:text-gray-200',
  [AttendanceStatus.PublicHoliday]: 'bg-purple-100 dark:bg-purple-800 text-purple-800 dark:text-purple-200',
  [AttendanceStatus.Weekend]: 'bg-gray-100 dark:bg-navy-900 text-gray-500',
  '': 'bg-white dark:bg-slate-800',
};
export const ATTENDANCE_STATUS_LABELS: Record<AttendanceStatus, string> = {
  [AttendanceStatus.Present]: 'Present',
  [AttendanceStatus.Absent]: 'Absent',
  [AttendanceStatus.AnnualLeave]: 'Annual Leave',
  [AttendanceStatus.SickLeave]: 'Sick Leave',
  [AttendanceStatus.EmergencyLeave]: 'Emergency Leave',
  [AttendanceStatus.UnpaidLeave]: 'Unpaid Leave',
  [AttendanceStatus.PublicHoliday]: 'Public Holiday',
  [AttendanceStatus.Weekend]: 'Weekend',
};


export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    attendance: 'Attendance',
    workers: 'Workers',
    users: 'Users',
    sites: 'Sites',
    reviews: 'Reviews',
    settings: 'Settings',
    logout: 'Logout',
    search: 'Search...',
    active_workers: 'Active Workers',
    active_sites: 'Active Sites',
    today_presence: "Today's Presence",
    today_absence: "Today's Absence",
    foreman_dashboard: 'Foreman Dashboard',
    your_workers: 'Your Workers',
    engineer_dashboard: 'Engineer Dashboard',
    review_cycle: 'Review Cycle',
    submit_for_review: 'Submit for Review',
    overtime: 'Overtime',
    addUser: 'Add User',
    editUser: 'Edit User',
    addSite: 'Add Site',
    editSite: 'Edit Site',
    siteName: 'Site Name',
    siteStatus: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    edit: 'Edit',
    delete: 'Delete',
    email: 'Email',
    password: 'Password',
    role: 'Role',
    login: 'Login',
    login_error: 'Invalid email or password.',
    welcome_back: 'Welcome Back',
    login_prompt: 'Please sign in to your account',
    fullName: 'Full Name',
    cancel: 'Cancel',
    saveUser: 'Save User',
    leaveBlank: 'Leave blank to keep current password',
    companySettings: 'Company Settings',
    companyName: 'Company Name',
    companyLogo: 'Company Logo',
    uploadLogo: 'Upload New Logo',
    saveChanges: 'Save Changes',
    dataExport: 'Data Export',
    exportDescription: 'Download a full attendance report for the current cycle in .xlsx format.',
    exportTimesheet: 'Export Timesheet (Excel)',
    changesSaved: 'Changes saved successfully.',
    exportInitiated: 'Excel export initiated.',
    status: 'Status',
    reviewStatus_pending: 'Pending',
    reviewStatus_submitted: 'Submitted',
    reviewStatus_approved: 'Approved',
    reviewStatus_returned: 'Returned',
    notesFromHr: 'Notes from HR',
    signOffAndSubmit: 'Sign-off and Submit',
    signHerePrompt: 'Please sign in the box below to confirm your review of this attendance cycle.',
    submitWarning: 'Once you submit, the cycle will be sent to HR for final approval. You will not be able to make further changes.',
    resubmitPrompt: 'Please re-sign to confirm you have reviewed the changes.',
    resubmitToHr: 'Re-submit to HR',
    goToReviewPage: 'Go to Review Page',
    cycleSubmitted: 'This cycle has been submitted and is awaiting HR approval.',
    cycleApproved: 'This cycle was approved by HR.',
    welcomeEngineer: 'Your primary task is to review and sign off on attendance cycles.',

  },
  ar: {
    dashboard: 'لوحة التحكم',
    attendance: 'الحضور',
    workers: 'العمال',
    users: 'المستخدمون',
    sites: 'المواقع',
    reviews: 'المراجعات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    search: 'بحث...',
    active_workers: 'العمال النشطون',
    active_sites: 'المواقع النشطة',
    today_presence: 'حضور اليوم',
    today_absence: 'غياب اليوم',
    foreman_dashboard: 'لوحة تحكم المشرف',
    your_workers: 'عمالك',
    engineer_dashboard: 'لوحة تحكم المهندس',
    review_cycle: 'مراجعة الدورة',
    submit_for_review: 'إرسال للمراجعة',
    overtime: 'عمل إضافي',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل مستخدم',
    addSite: 'إضافة موقع',
    editSite: 'تعديل الموقع',
    siteName: 'اسم الموقع',
    siteStatus: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    edit: 'تعديل',
    delete: 'حذف',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    role: 'الدور',
    login: 'تسجيل الدخول',
    login_error: 'البريد الإلكتروني أو كلمة المرور غير صالحة.',
    welcome_back: 'أهلاً بعودتك',
    login_prompt: 'الرجاء تسجيل الدخول إلى حسابك',
    fullName: 'الاسم الكامل',
    cancel: 'إلغاء',
    saveUser: 'حفظ المستخدم',
    leaveBlank: 'اتركه فارغاً للإبقاء على كلمة المرور الحالية',
    companySettings: 'إعدادات الشركة',
    companyName: 'اسم الشركة',
    companyLogo: 'شعار الشركة',
    uploadLogo: 'تحميل شعار جديد',
    saveChanges: 'حفظ التغييرات',
    dataExport: 'تصدير البيانات',
    exportDescription: 'تنزيل تقرير حضور كامل للدورة الحالية بصيغة .xlsx.',
    exportTimesheet: 'تصدير جدول الحضور (Excel)',
    changesSaved: 'تم حفظ التغييرات بنجاح.',
    exportInitiated: 'بدء تصدير ملف Excel.',
    status: 'الحالة',
    reviewStatus_pending: 'قيد الانتظار',
    reviewStatus_submitted: 'تم الإرسال',
    reviewStatus_approved: 'تمت الموافقة',
    reviewStatus_returned: 'مُعاد',
    notesFromHr: 'ملاحظات من الموارد البشرية',
    signOffAndSubmit: 'التوقيع والإرسال',
    signHerePrompt: 'يرجى التوقيع في المربع أدناه لتأكيد مراجعتك لهذه الدورة.',
    submitWarning: 'بمجرد الإرسال، سيتم إرسال الدورة إلى الموارد البشرية للموافقة النهائية. لن تتمكن من إجراء المزيد من التغييرات.',
    resubmitPrompt: 'يرجى إعادة التوقيع لتأكيد مراجعتك للتغييرات.',
    resubmitToHr: 'إعادة الإرسال للموارد البشرية',
    goToReviewPage: 'الانتقال إلى صفحة المراجعة',
    cycleSubmitted: 'تم إرسال هذه الدورة وهي في انتظار موافقة الموارد البشرية.',
    cycleApproved: 'تمت الموافقة على هذه الدورة من قبل الموارد البشرية.',
    welcomeEngineer: 'مهمتك الأساسية هي مراجعة دورات الحضور والتوقيع عليها.',
  }
};